# name: Go

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# jobs:

#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3

      
#     - uses: "marvinpinto/action-automatic-releases@latest"
#       with:
#         repo_token: "${{ secrets.GITHUB_TOKEN }}"
#         automatic_release_tag: "v0.5"
#         prerelease: false
#         title: "v0.5"
#         files: |
#           *.*
